name: bartr
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+6

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  another_flushbar: ^1.10.29
  auto_route: ^5.0.1
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.0.5
  country_calling_code_picker: ^2.0.1
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.7
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_countdown_timer: ^4.1.0
  flutter_hooks: ^0.18.5+1
  flutter_mentions: ^2.0.1
  flutter_svg: ^1.1.1+1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.1.1
  http_mock_adapter: ^0.3.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  linkfy_text: ^1.1.5
  mockito: ^5.3.2
  new_version_plus: ^0.0.4
  pattern_formatter: ^2.0.0
  pin_code_text_field: ^1.8.0
  retrofit: ^3.0.1+1
  scroll_to_index: ^3.0.1
  share_plus: ^6.0.0
  timeago_flutter: ^1.2.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.5

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.3.2
  retrofit_generator: ^4.0.3+2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/release_logo.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
