// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeMLNI91P7LXsMzexzvwm7QbjAs7OQXcI',
    appId: '1:46597783899:web:4cef239ffb3ac28e791a7e',
    messagingSenderId: '46597783899',
    projectId: 'bartr-8fa2f',
    authDomain: 'bartr-8fa2f.firebaseapp.com',
    storageBucket: 'bartr-8fa2f.appspot.com',
    measurementId: 'G-D7VL3B16SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3wYbBFbSqgfoPhgjtDFhPFE157Vlf_NA',
    appId: '1:46597783899:android:cd97d440bb7b2005791a7e',
    messagingSenderId: '46597783899',
    projectId: 'bartr-8fa2f',
    storageBucket: 'bartr-8fa2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa_L_ZefupkPEn3pdNZZ8Sj5pQpr0FSUc',
    appId: '1:46597783899:ios:824f438f4579cc34791a7e',
    messagingSenderId: '46597783899',
    projectId: 'bartr-8fa2f',
    storageBucket: 'bartr-8fa2f.appspot.com',
    iosClientId: '46597783899-dral2eogjn1nlm10ng2pf8qdgalqqtat.apps.googleusercontent.com',
    iosBundleId: 'com.mybartr.bartrapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa_L_ZefupkPEn3pdNZZ8Sj5pQpr0FSUc',
    appId: '1:46597783899:ios:824f438f4579cc34791a7e',
    messagingSenderId: '46597783899',
    projectId: 'bartr-8fa2f',
    storageBucket: 'bartr-8fa2f.appspot.com',
    iosClientId: '46597783899-dral2eogjn1nlm10ng2pf8qdgalqqtat.apps.googleusercontent.com',
    iosBundleId: 'com.mybartr.bartrapp',
  );
}
